// Code generated by stanc v2.33.1
#include <stan/model/model_header.hpp>
namespace transform_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 58> locations_array__ =
  {" (found before start of program)",
  " (in 'transform.stan', line 21, column 4 to column 32)",
  " (in 'transform.stan', line 22, column 4 to column 32)",
  " (in 'transform.stan', line 25, column 4 to column 22)",
  " (in 'transform.stan', line 26, column 4 to column 22)",
  " (in 'transform.stan', line 29, column 8 to column 53)",
  " (in 'transform.stan', line 28, column 4 to line 29, column 53)",
  " (in 'transform.stan', line 31, column 8 to column 53)",
  " (in 'transform.stan', line 30, column 4 to line 31, column 53)",
  " (in 'transform.stan', line 34, column 4 to column 14)",
  " (in 'transform.stan', line 35, column 4 to column 21)",
  " (in 'transform.stan', line 36, column 4 to column 14)",
  " (in 'transform.stan', line 37, column 4 to column 21)",
  " (in 'transform.stan', line 40, column 8 to column 39)",
  " (in 'transform.stan', line 39, column 4 to line 40, column 39)",
  " (in 'transform.stan', line 45, column 16 to column 73)",
  " (in 'transform.stan', line 46, column 2 to column 51)",
  " (in 'transform.stan', line 48, column 16 to column 57)",
  " (in 'transform.stan', line 44, column 35 to line 49, column 13)",
  " (in 'transform.stan', line 44, column 12 to line 49, column 13)",
  " (in 'transform.stan', line 43, column 25 to line 50, column 9)",
  " (in 'transform.stan', line 43, column 8 to line 50, column 9)",
  " (in 'transform.stan', line 42, column 18 to line 51, column 5)",
  " (in 'transform.stan', line 42, column 4 to line 51, column 5)",
  " (in 'transform.stan', line 55, column 16 to column 80)",
  " (in 'transform.stan', line 56, column 2 to column 58)",
  " (in 'transform.stan', line 57, column 16 to column 78)",
  " (in 'transform.stan', line 54, column 42 to line 58, column 13)",
  " (in 'transform.stan', line 54, column 12 to line 58, column 13)",
  " (in 'transform.stan', line 53, column 23 to line 59, column 9)",
  " (in 'transform.stan', line 53, column 8 to line 59, column 9)",
  " (in 'transform.stan', line 52, column 18 to line 60, column 5)",
  " (in 'transform.stan', line 52, column 4 to line 60, column 5)",
  " (in 'transform.stan', line 11, column 4 to column 20)",
  " (in 'transform.stan', line 12, column 4 to column 20)",
  " (in 'transform.stan', line 13, column 4 to column 19)",
  " (in 'transform.stan', line 14, column 4 to column 29)",
  " (in 'transform.stan', line 15, column 10 to column 12)",
  " (in 'transform.stan', line 15, column 21 to column 22)",
  " (in 'transform.stan', line 15, column 4 to column 32)",
  " (in 'transform.stan', line 16, column 22 to column 24)",
  " (in 'transform.stan', line 16, column 4 to column 32)",
  " (in 'transform.stan', line 17, column 11 to column 13)",
  " (in 'transform.stan', line 17, column 15 to column 17)",
  " (in 'transform.stan', line 17, column 4 to column 34)",
  " (in 'transform.stan', line 18, column 11 to column 13)",
  " (in 'transform.stan', line 18, column 15 to column 17)",
  " (in 'transform.stan', line 18, column 4 to column 27)",
  " (in 'transform.stan', line 21, column 10 to column 12)",
  " (in 'transform.stan', line 21, column 21 to column 22)",
  " (in 'transform.stan', line 22, column 22 to column 24)",
  " (in 'transform.stan', line 25, column 11 to column 13)",
  " (in 'transform.stan', line 26, column 11 to column 13)",
  " (in 'transform.stan', line 3, column 12 to column 50)",
  " (in 'transform.stan', line 7, column 16 to column 27)",
  " (in 'transform.stan', line 5, column 16 to column 58)",
  " (in 'transform.stan', line 4, column 12 to line 7, column 27)",
  " (in 'transform.stan', line 2, column 52 to line 8, column 7)"};
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>>* = nullptr>
stan::promote_args_t<T0__, T1__, stan::base_type_t<T2__>,
  stan::base_type_t<T3__>>
hyp(const T0__& t1, const T1__& t2, const T2__& E1_arg__, const T3__&
    E2_arg__, std::ostream* pstream__);
// real hyp(real, real, vector, vector)
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>>*>
stan::promote_args_t<T0__, T1__, stan::base_type_t<T2__>,
  stan::base_type_t<T3__>>
hyp(const T0__& t1, const T1__& t2, const T2__& E1_arg__, const T3__&
    E2_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& E1 = stan::math::to_ref(E1_arg__);
  const auto& E2 = stan::math::to_ref(E2_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ xi = DUMMY_VAR__;
    current_statement__ = 53;
    xi = ((t1 * t2) - stan::math::dot_product(E1, E2));
    current_statement__ = 56;
    if (stan::math::logical_gt(xi, 1)) {
      current_statement__ = 55;
      return stan::math::acosh(((t1 * t2) - stan::math::dot_product(E1, E2)));
    } else {
      current_statement__ = 54;
      return 0.0;
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
class transform_model final : public model_base_crtp<transform_model> {
 private:
  int Ne;
  int Nn;
  int D;
  double lambda;
  std::vector<Eigen::Matrix<double,-1,1>> euc_emb;
  Eigen::Matrix<double,-1,1> sig_e_data__;
  Eigen::Matrix<double,-1,-1> deltaij_mutual_data__;
  Eigen::Matrix<double,-1,-1> deltaij_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> sig_e{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> deltaij_mutual{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> deltaij{nullptr, 0, 0};
 public:
  ~transform_model() {}
  transform_model(stan::io::var_context& context__, unsigned int
                  random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "transform_model_namespace::transform_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 33;
      context__.validate_dims("data initialization", "Ne", "int",
        std::vector<size_t>{});
      Ne = std::numeric_limits<int>::min();
      current_statement__ = 33;
      Ne = context__.vals_i("Ne")[(1 - 1)];
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "Ne", Ne, 0);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "Nn", "int",
        std::vector<size_t>{});
      Nn = std::numeric_limits<int>::min();
      current_statement__ = 34;
      Nn = context__.vals_i("Nn")[(1 - 1)];
      current_statement__ = 34;
      stan::math::check_greater_or_equal(function__, "Nn", Nn, 0);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "D", "int",
        std::vector<size_t>{});
      D = std::numeric_limits<int>::min();
      current_statement__ = 35;
      D = context__.vals_i("D")[(1 - 1)];
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "D", D, 0);
      current_statement__ = 36;
      context__.validate_dims("data initialization", "lambda", "double",
        std::vector<size_t>{});
      lambda = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 36;
      lambda = context__.vals_r("lambda")[(1 - 1)];
      current_statement__ = 36;
      stan::math::check_greater_or_equal(function__, "lambda", lambda, 0.001);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("euc_emb", "Ne", Ne);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("euc_emb", "D", D);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "euc_emb", "double",
        std::vector<size_t>{static_cast<size_t>(Ne), static_cast<size_t>(D)});
      euc_emb = std::vector<Eigen::Matrix<double,-1,1>>(Ne,
                  Eigen::Matrix<double,-1,1>::Constant(D,
                    std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> euc_emb_flat__;
        current_statement__ = 39;
        euc_emb_flat__ = context__.vals_r("euc_emb");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= Ne; ++sym2__) {
            stan::model::assign(euc_emb, euc_emb_flat__[(pos__ - 1)],
              "assigning variable euc_emb", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 40;
      stan::math::validate_non_negative_index("sig_e", "Ne", Ne);
      current_statement__ = 41;
      context__.validate_dims("data initialization", "sig_e", "double",
        std::vector<size_t>{static_cast<size_t>(Ne)});
      sig_e_data__ = Eigen::Matrix<double,-1,1>::Constant(Ne,
                       std::numeric_limits<double>::quiet_NaN());
      new (&sig_e)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(sig_e_data__.data(), Ne);
      {
        std::vector<local_scalar_t__> sig_e_flat__;
        current_statement__ = 41;
        sig_e_flat__ = context__.vals_r("sig_e");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= Ne; ++sym1__) {
          stan::model::assign(sig_e, sig_e_flat__[(pos__ - 1)],
            "assigning variable sig_e", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 41;
      stan::math::check_greater_or_equal(function__, "sig_e", sig_e, 0.0);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("deltaij_mutual", "Nn", Nn);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("deltaij_mutual", "Ne", Ne);
      current_statement__ = 44;
      context__.validate_dims("data initialization", "deltaij_mutual",
        "double",
        std::vector<size_t>{static_cast<size_t>(Nn), static_cast<size_t>(Ne)});
      deltaij_mutual_data__ = Eigen::Matrix<double,-1,-1>::Constant(Nn, Ne,
                                std::numeric_limits<double>::quiet_NaN());
      new (&deltaij_mutual)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(deltaij_mutual_data__.data(),
        Nn, Ne);
      {
        std::vector<local_scalar_t__> deltaij_mutual_flat__;
        current_statement__ = 44;
        deltaij_mutual_flat__ = context__.vals_r("deltaij_mutual");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= Ne; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= Nn; ++sym2__) {
            stan::model::assign(deltaij_mutual, deltaij_mutual_flat__[(pos__
              - 1)], "assigning variable deltaij_mutual",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 45;
      stan::math::validate_non_negative_index("deltaij", "Nn", Nn);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("deltaij", "Nn", Nn);
      current_statement__ = 47;
      context__.validate_dims("data initialization", "deltaij", "double",
        std::vector<size_t>{static_cast<size_t>(Nn), static_cast<size_t>(Nn)});
      deltaij_data__ = Eigen::Matrix<double,-1,-1>::Constant(Nn, Nn,
                         std::numeric_limits<double>::quiet_NaN());
      new (&deltaij)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(deltaij_data__.data(), Nn,
        Nn);
      {
        std::vector<local_scalar_t__> deltaij_flat__;
        current_statement__ = 47;
        deltaij_flat__ = context__.vals_r("deltaij");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= Nn; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= Nn; ++sym2__) {
            stan::model::assign(deltaij, deltaij_flat__[(pos__ - 1)],
              "assigning variable deltaij", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 48;
      stan::math::validate_non_negative_index("euc_new", "Nn", Nn);
      current_statement__ = 49;
      stan::math::validate_non_negative_index("euc_new", "D", D);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("sig_n", "Nn", Nn);
      current_statement__ = 51;
      stan::math::validate_non_negative_index("time_e", "Ne", Ne);
      current_statement__ = 52;
      stan::math::validate_non_negative_index("time_n", "Nn", Nn);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (Nn * D) + Nn;
  }
  inline std::string model_name() const final {
    return "transform_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.33.1",
             "stancflags = --filename-in-msg=transform.stan"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "transform_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> euc_new =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(Nn,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__));
      current_statement__ = 1;
      euc_new = in__.template read<
                  std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(Nn, D);
      Eigen::Matrix<local_scalar_t__,-1,1> sig_n =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(Nn, DUMMY_VAR__);
      current_statement__ = 2;
      sig_n = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0.0, lp__,
                Nn);
      Eigen::Matrix<local_scalar_t__,-1,1> time_e =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(Ne, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> time_n =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(Nn, DUMMY_VAR__);
      current_statement__ = 6;
      for (int i = 1; i <= Ne; ++i) {
        current_statement__ = 5;
        stan::model::assign(time_e,
          stan::math::sqrt((1.0 +
            stan::math::dot_self(
              stan::model::rvalue(euc_emb, "euc_emb",
                stan::model::index_uni(i))))), "assigning variable time_e",
          stan::model::index_uni(i));
      }
      current_statement__ = 8;
      for (int i = 1; i <= Nn; ++i) {
        current_statement__ = 7;
        stan::model::assign(time_n,
          stan::math::sqrt((1.0 +
            stan::math::dot_self(
              stan::model::rvalue(euc_new, "euc_new",
                stan::model::index_uni(i))))), "assigning variable time_n",
          stan::model::index_uni(i));
      }
      {
        local_scalar_t__ dist = DUMMY_VAR__;
        local_scalar_t__ dist_mutual = DUMMY_VAR__;
        local_scalar_t__ seff = DUMMY_VAR__;
        local_scalar_t__ seff_mutual = DUMMY_VAR__;
        current_statement__ = 14;
        for (int i = 1; i <= Nn; ++i) {
          current_statement__ = 13;
          lp_accum__.add(stan::math::inv_gamma_lpdf<propto__>(
                           stan::model::rvalue(sig_n, "sig_n",
                             stan::model::index_uni(i)), 2.0, 0.5));
        }
        current_statement__ = 23;
        for (int i = 1; i <= Nn; ++i) {
          current_statement__ = 21;
          for (int j = (i + 1); j <= Nn; ++j) {
            current_statement__ = 19;
            if (stan::math::logical_gt(
                  stan::model::rvalue(deltaij, "deltaij",
                    stan::model::index_uni(i), stan::model::index_uni(j)),
                  0.0)) {
              current_statement__ = 15;
              dist = hyp(
                       stan::model::rvalue(time_n, "time_n",
                         stan::model::index_uni(i)),
                       stan::model::rvalue(time_n, "time_n",
                         stan::model::index_uni(j)),
                       stan::model::rvalue(euc_new, "euc_new",
                         stan::model::index_uni(i)),
                       stan::model::rvalue(euc_new, "euc_new",
                         stan::model::index_uni(j)), pstream__);
              current_statement__ = 16;
              seff = stan::math::sqrt(
                       (stan::math::square(
                          stan::model::rvalue(sig_n, "sig_n",
                            stan::model::index_uni(i))) +
                       stan::math::square(
                         stan::model::rvalue(sig_n, "sig_n",
                           stan::model::index_uni(j)))));
              current_statement__ = 17;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(deltaij, "deltaij",
                                 stan::model::index_uni(i),
                                 stan::model::index_uni(j)), (dist / lambda),
                               seff));
            }
          }
        }
        current_statement__ = 32;
        for (int i = 1; i <= Nn; ++i) {
          current_statement__ = 30;
          for (int j = 1; j <= Ne; ++j) {
            current_statement__ = 28;
            if (stan::math::logical_gt(
                  stan::model::rvalue(deltaij_mutual, "deltaij_mutual",
                    stan::model::index_uni(i), stan::model::index_uni(j)),
                  0.0)) {
              current_statement__ = 24;
              dist_mutual = hyp(
                              stan::model::rvalue(time_n, "time_n",
                                stan::model::index_uni(i)),
                              stan::model::rvalue(time_e, "time_e",
                                stan::model::index_uni(j)),
                              stan::model::rvalue(euc_new, "euc_new",
                                stan::model::index_uni(i)),
                              stan::model::rvalue(euc_emb, "euc_emb",
                                stan::model::index_uni(j)), pstream__);
              current_statement__ = 25;
              seff_mutual = stan::math::sqrt(
                              (stan::math::square(
                                 stan::model::rvalue(sig_n, "sig_n",
                                   stan::model::index_uni(i))) +
                              stan::math::square(
                                stan::model::rvalue(sig_e, "sig_e",
                                  stan::model::index_uni(j)))));
              current_statement__ = 26;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(deltaij_mutual,
                                 "deltaij_mutual", stan::model::index_uni(i),
                                 stan::model::index_uni(j)), (dist_mutual /
                               lambda), seff_mutual));
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "transform_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> euc_new =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(Nn,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__));
      current_statement__ = 1;
      euc_new = in__.template read<
                  std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(Nn, D);
      Eigen::Matrix<local_scalar_t__,-1,1> sig_n =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(Nn, DUMMY_VAR__);
      current_statement__ = 2;
      sig_n = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0.0, lp__,
                Nn);
      Eigen::Matrix<local_scalar_t__,-1,1> time_e =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(Ne, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> time_n =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(Nn, DUMMY_VAR__);
      current_statement__ = 6;
      for (int i = 1; i <= Ne; ++i) {
        current_statement__ = 5;
        stan::model::assign(time_e,
          stan::math::sqrt((1.0 +
            stan::math::dot_self(
              stan::model::rvalue(euc_emb, "euc_emb",
                stan::model::index_uni(i))))), "assigning variable time_e",
          stan::model::index_uni(i));
      }
      current_statement__ = 8;
      for (int i = 1; i <= Nn; ++i) {
        current_statement__ = 7;
        stan::model::assign(time_n,
          stan::math::sqrt((1.0 +
            stan::math::dot_self(
              stan::model::rvalue(euc_new, "euc_new",
                stan::model::index_uni(i))))), "assigning variable time_n",
          stan::model::index_uni(i));
      }
      {
        local_scalar_t__ dist = DUMMY_VAR__;
        local_scalar_t__ dist_mutual = DUMMY_VAR__;
        local_scalar_t__ seff = DUMMY_VAR__;
        local_scalar_t__ seff_mutual = DUMMY_VAR__;
        current_statement__ = 14;
        for (int i = 1; i <= Nn; ++i) {
          current_statement__ = 13;
          lp_accum__.add(stan::math::inv_gamma_lpdf<propto__>(
                           stan::model::rvalue(sig_n, "sig_n",
                             stan::model::index_uni(i)), 2.0, 0.5));
        }
        current_statement__ = 23;
        for (int i = 1; i <= Nn; ++i) {
          current_statement__ = 21;
          for (int j = (i + 1); j <= Nn; ++j) {
            current_statement__ = 19;
            if (stan::math::logical_gt(
                  stan::model::rvalue(deltaij, "deltaij",
                    stan::model::index_uni(i), stan::model::index_uni(j)),
                  0.0)) {
              current_statement__ = 15;
              dist = hyp(
                       stan::model::rvalue(time_n, "time_n",
                         stan::model::index_uni(i)),
                       stan::model::rvalue(time_n, "time_n",
                         stan::model::index_uni(j)),
                       stan::model::rvalue(euc_new, "euc_new",
                         stan::model::index_uni(i)),
                       stan::model::rvalue(euc_new, "euc_new",
                         stan::model::index_uni(j)), pstream__);
              current_statement__ = 16;
              seff = stan::math::sqrt(
                       (stan::math::square(
                          stan::model::rvalue(sig_n, "sig_n",
                            stan::model::index_uni(i))) +
                       stan::math::square(
                         stan::model::rvalue(sig_n, "sig_n",
                           stan::model::index_uni(j)))));
              current_statement__ = 17;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(deltaij, "deltaij",
                                 stan::model::index_uni(i),
                                 stan::model::index_uni(j)), (dist / lambda),
                               seff));
            }
          }
        }
        current_statement__ = 32;
        for (int i = 1; i <= Nn; ++i) {
          current_statement__ = 30;
          for (int j = 1; j <= Ne; ++j) {
            current_statement__ = 28;
            if (stan::math::logical_gt(
                  stan::model::rvalue(deltaij_mutual, "deltaij_mutual",
                    stan::model::index_uni(i), stan::model::index_uni(j)),
                  0.0)) {
              current_statement__ = 24;
              dist_mutual = hyp(
                              stan::model::rvalue(time_n, "time_n",
                                stan::model::index_uni(i)),
                              stan::model::rvalue(time_e, "time_e",
                                stan::model::index_uni(j)),
                              stan::model::rvalue(euc_new, "euc_new",
                                stan::model::index_uni(i)),
                              stan::model::rvalue(euc_emb, "euc_emb",
                                stan::model::index_uni(j)), pstream__);
              current_statement__ = 25;
              seff_mutual = stan::math::sqrt(
                              (stan::math::square(
                                 stan::model::rvalue(sig_n, "sig_n",
                                   stan::model::index_uni(i))) +
                              stan::math::square(
                                stan::model::rvalue(sig_e, "sig_e",
                                  stan::model::index_uni(j)))));
              current_statement__ = 26;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(deltaij_mutual,
                                 "deltaij_mutual", stan::model::index_uni(i),
                                 stan::model::index_uni(j)), (dist_mutual /
                               lambda), seff_mutual));
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "transform_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<Eigen::Matrix<double,-1,1>> euc_new =
        std::vector<Eigen::Matrix<double,-1,1>>(Nn,
          Eigen::Matrix<double,-1,1>::Constant(D,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 1;
      euc_new = in__.template read<
                  std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(Nn, D);
      Eigen::Matrix<double,-1,1> sig_n =
        Eigen::Matrix<double,-1,1>::Constant(Nn,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      sig_n = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0.0, lp__,
                Nn);
      Eigen::Matrix<double,-1,1> time_e =
        Eigen::Matrix<double,-1,1>::Constant(Ne,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> time_n =
        Eigen::Matrix<double,-1,1>::Constant(Nn,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= Nn; ++sym2__) {
          out__.write(euc_new[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      out__.write(sig_n);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 6;
      for (int i = 1; i <= Ne; ++i) {
        current_statement__ = 5;
        stan::model::assign(time_e,
          stan::math::sqrt((1.0 +
            stan::math::dot_self(
              stan::model::rvalue(euc_emb, "euc_emb",
                stan::model::index_uni(i))))), "assigning variable time_e",
          stan::model::index_uni(i));
      }
      current_statement__ = 8;
      for (int i = 1; i <= Nn; ++i) {
        current_statement__ = 7;
        stan::model::assign(time_n,
          stan::math::sqrt((1.0 +
            stan::math::dot_self(
              stan::model::rvalue(euc_new, "euc_new",
                stan::model::index_uni(i))))), "assigning variable time_n",
          stan::model::index_uni(i));
      }
      if (emit_transformed_parameters__) {
        out__.write(time_e);
        out__.write(time_n);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> euc_new =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(Nn,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__));
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= Nn; ++sym2__) {
          current_statement__ = 1;
          stan::model::assign(euc_new, in__.read<local_scalar_t__>(),
            "assigning variable euc_new", stan::model::index_uni(sym2__),
            stan::model::index_uni(sym1__));
        }
      }
      out__.write(euc_new);
      Eigen::Matrix<local_scalar_t__,-1,1> sig_n =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(Nn, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(sig_n,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(Nn),
        "assigning variable sig_n");
      out__.write_free_lb(0.0, sig_n);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "euc_new",
        "double",
        std::vector<size_t>{static_cast<size_t>(Nn), static_cast<size_t>(D)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sig_n", "double",
        std::vector<size_t>{static_cast<size_t>(Nn)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> euc_new =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(Nn,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> euc_new_flat__;
        current_statement__ = 1;
        euc_new_flat__ = context__.vals_r("euc_new");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= Nn; ++sym2__) {
            stan::model::assign(euc_new, euc_new_flat__[(pos__ - 1)],
              "assigning variable euc_new", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(euc_new);
      Eigen::Matrix<local_scalar_t__,-1,1> sig_n =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(Nn, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sig_n_flat__;
        current_statement__ = 2;
        sig_n_flat__ = context__.vals_r("sig_n");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= Nn; ++sym1__) {
          stan::model::assign(sig_n, sig_n_flat__[(pos__ - 1)],
            "assigning variable sig_n", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0.0, sig_n);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"euc_new", "sig_n"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"time_e", "time_n"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    Nn),
                                                 static_cast<size_t>(D)},
                std::vector<size_t>{static_cast<size_t>(Nn)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(Ne)},
             std::vector<size_t>{static_cast<size_t>(Nn)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= Nn; ++sym2__) {
        param_names__.emplace_back(std::string() + "euc_new" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= Nn; ++sym1__) {
      param_names__.emplace_back(std::string() + "sig_n" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= Ne; ++sym1__) {
        param_names__.emplace_back(std::string() + "time_e" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= Nn; ++sym1__) {
        param_names__.emplace_back(std::string() + "time_n" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= Nn; ++sym2__) {
        param_names__.emplace_back(std::string() + "euc_new" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= Nn; ++sym1__) {
      param_names__.emplace_back(std::string() + "sig_n" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= Ne; ++sym1__) {
        param_names__.emplace_back(std::string() + "time_e" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= Nn; ++sym1__) {
        param_names__.emplace_back(std::string() + "time_n" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"euc_new\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nn) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "}},\"block\":\"parameters\"},{\"name\":\"sig_n\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Nn) + "},\"block\":\"parameters\"},{\"name\":\"time_e\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Ne) + "},\"block\":\"transformed_parameters\"},{\"name\":\"time_n\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Nn) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"euc_new\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nn) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "}},\"block\":\"parameters\"},{\"name\":\"sig_n\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Nn) + "},\"block\":\"parameters\"},{\"name\":\"time_e\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Ne) + "},\"block\":\"transformed_parameters\"},{\"name\":\"time_n\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Nn) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((Nn * D) + Nn);
    const size_t num_transformed = emit_transformed_parameters * ((Ne + Nn));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((Nn * D) + Nn);
    const size_t num_transformed = emit_transformed_parameters * ((Ne + Nn));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = transform_model_namespace::transform_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return transform_model_namespace::profiles__;
}
#endif